### ISSUE TITLE
TNC4 compatibility?

### ISSUE THREAD

**Issue by btcbobby** [mobilinkd/m17-kiss-ht#1]
I am getting immediate disconnects when using with TNC4. I am sometimes able to get connected when app auto deletes pairing with TNC4 and tries to pair on its own. Then I get RX but no TX out even when Transmit button tapped no PTT or VOX to radio

**Comment by mobilinkd** [comment]
See if this helps: https://groups.io/g/mobilinkd/message/3676

I have not had time to work on this. Hopefully I can do that soon.

**Comment by btcbobby** [comment]
Thank you! It got me further along, it now transmits but will not unkey. VOX is off and tried on two different radios. Primary radio I am testing with is Anyone 878-II Plus

**Comment by mobilinkd** [comment]
You cannot use an HT for this. M17 requires a 9600 baud capable radio.

**Comment by btcbobby** [comment]
Ah, sorry about that! I have a 991a, I'll try that next. Thank you!
